id: c1dbed73270a4d9fa57ee848c60c8d4c
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_729-Dh%C4%81ra%E1%B9%87%C4%AB_of_T%C4%81r%C4%81-v2
  language: bo
  author: ''
  volume: {}
